### ISSUE TITLE
Linux (Ubuntu 14.04) workaround

### ISSUE THREAD

**Issue by zpodlovics** [enricosada/fsharp-dotnet-cli-samples#4]
I managed to get it working on Linux (Ubuntu14.04) using your Mac OS X workaround + additional workaround to fix the missing mscorlib ref.

Steps to reproduce (Ubuntu 14.04 x86_64, dotnet 1.0.0.001638-1 installed):

1) Unpack the F# compiler.
```
cd /usr/share/dotnet/bin 
unzip /path/to/osx.10.10-x64.zip 
```
Overwrite fsc.exe, FSharp.Compiler.dll, FSharp.Core.dll

2) Create new F# project
```
dotnet new --lang fsharp
dotnet restore
```
3) Compile the F# project (it will fail due the missing mscorlib.dll ref):
```
/usr/share/dotnet/bin/dotnet compile-fsc @/tmp/coreclr/obj/Debug/netstandardapp1.5/dotnet-compile.rsp returned Exit Code 1
/tmp/coreclr/unknown(1,1): error FS0078: Unable to find the file 'mscorlib.dll' in any of
/tmp/coreclr/unknown(1,1): error FS0078: Unable to find the file 'mscorlib.dll' in any of
```

4) Get your mscorlib.dll path (pick the newest)

find $HOME/.nuget/|grep mscorlib

eg.:
/home/demo/.nuget/packages/runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.2-rc2-23901/runtimes/ubuntu.14.04-x64/lib/dotnet/mscorlib.dll

5) Edit your rsp file (/tmp/coreclr/obj/Debug/netstandardapp1.5/dotnet-compile.rsp) and add the missing mscorlib.dll ref and the end but before the "/tmp/coreclr/Program.fs" line

```
--temp-output:/tmp/coreclr/obj/Debug/netstandardapp1.5/
--out:/tmp/coreclr/bin/Debug/netstandardapp1.5/coreclr.dll
--define:DEBUG
--define:TRACE
--define:NETSTANDARDAPP1_5
--optimize:False
--emit-entry-point:True
--file-version:1.0.0.0
--version:1.0.0.0
--informational-version:1.0.0
--target-framework:.NETStandardApp,Version=v1.5
--reference:/home/demo/.nuget/packages/Microsoft.FSharp.Core.netcore/1.0.0-alpha-151221/lib/DNXCore50/FSharp.Core.dll
--reference:/home/demo/.nuget/packages/Microsoft.Win32.Primitives/4.0.1-rc2-23901/ref/netstandard1.3/Microsoft.Win32.Primitives.dll
--reference:/home/demo/.nuget/packages/System.AppContext/4.1.0-rc2-23901/ref/netstandard1.5/System.AppContext.dll
--reference:/home/demo/.nuget/packages/System.Collections/4.0.11-rc2-23901/ref/netstandard1.3/System.Collections.dll
--reference:/home/demo/.nuget/packages/System.Collections.Concurrent/4.0.12-rc2-23901/ref/netstandard1.3/System.Collections.Concurrent.dll
--reference:/home/demo/.nuget/packages/System.Collections.NonGeneric/4.0.0/ref/dotnet/System.Collections.NonGeneric.dll
--reference:/home/demo/.nuget/packages/System.Collections.Specialized/4.0.0/ref/dotnet/System.Collections.Specialized.dll
--reference:/home/demo/.nuget/packages/System.Console/4.0.0-rc2-23901/ref/netstandard1.3/System.Console.dll
--reference:/home/demo/.nuget/packages/System.Diagnostics.Debug/4.0.11-rc2-23901/ref/netstandard1.3/System.Diagnostics.Debug.dll
--reference:/home/demo/.nuget/packages/System.Diagnostics.Process/4.1.0-rc2-23616/ref/dotnet5.5/System.Diagnostics.Process.dll
--reference:/home/demo/.nuget/packages/System.Diagnostics.Tools/4.0.1-rc2-23901/ref/netstandard1.0/System.Diagnostics.Tools.dll
--reference:/home/demo/.nuget/packages/System.Diagnostics.Tracing/4.1.0-rc2-23901/ref/netstandard1.5/System.Diagnostics.Tracing.dll
--reference:/home/demo/.nuget/packages/System.Globalization/4.0.11-rc2-23901/ref/netstandard1.3/System.Globalization.dll
--reference:/home/demo/.nuget/packages/System.Globalization.Calendars/4.0.1-rc2-23901/ref/netstandard1.3/System.Globalization.Calendars.dll
--reference:/home/demo/.nuget/packages/System.Globalization.Extensions/4.0.0/ref/dotnet/System.Globalization.Extensions.dll
--reference:/home/demo/.nuget/packages/System.IO/4.1.0-rc2-23901/ref/netstandard1.3/System.IO.dll
--reference:/home/demo/.nuget/packages/System.IO.FileSystem/4.0.1-rc2-23901/ref/netstandard1.3/System.IO.FileSystem.dll
--reference:/home/demo/.nuget/packages/System.IO.FileSystem.Primitives/4.0.1-rc2-23901/ref/netstandard1.3/System.IO.FileSystem.Primitives.dll
--reference:/home/demo/.nuget/packages/System.Linq/4.1.0-rc2-23901/ref/netstandard1.5/System.Linq.dll
--reference:/home/demo/.nuget/packages/System.Linq.Expressions/4.0.11-rc2-23616/ref/dotnet5.4/System.Linq.Expressions.dll
--reference:/home/demo/.nuget/packages/System.Linq.Queryable/4.0.1-rc2-23616/ref/dotnet5.1/System.Linq.Queryable.dll
--reference:/home/demo/.nuget/packages/System.Net.Primitives/4.0.11-rc2-23901/ref/netstandard1.3/System.Net.Primitives.dll
--reference:/home/demo/.nuget/packages/System.Net.Requests/4.0.11-rc2-23616/ref/dotnet5.4/System.Net.Requests.dll
--reference:/home/demo/.nuget/packages/System.Net.Sockets/4.1.0-rc2-23901/ref/netstandard1.3/System.Net.Sockets.dll
--reference:/home/demo/.nuget/packages/System.Net.WebHeaderCollection/4.0.0/ref/dotnet/System.Net.WebHeaderCollection.dll
--reference:/home/demo/.nuget/packages/System.Reflection/4.1.0-rc2-23901/ref/netstandard1.3/System.Reflection.dll
--reference:/home/demo/.nuget/packages/System.Reflection.Emit/4.0.1-rc2-23616/ref/dotnet5.2/System.Reflection.Emit.dll
--reference:/home/demo/.nuget/packages/System.Reflection.Emit.ILGeneration/4.0.1-rc2-23616/ref/dotnet5.1/System.Reflection.Emit.ILGeneration.dll
--reference:/home/demo/.nuget/packages/System.Reflection.Extensions/4.0.1-rc2-23901/ref/netstandard1.0/System.Reflection.Extensions.dll
--reference:/home/demo/.nuget/packages/System.Reflection.Primitives/4.0.1-rc2-23901/ref/netstandard1.0/System.Reflection.Primitives.dll
--reference:/home/demo/.nuget/packages/System.Reflection.TypeExtensions/4.1.0-rc2-23901/ref/netstandard1.3/System.Reflection.TypeExtensions.dll
--reference:/home/demo/.nuget/packages/System.Resources.ResourceManager/4.0.1-rc2-23901/ref/netstandard1.0/System.Resources.ResourceManager.dll
--reference:/home/demo/.nuget/packages/System.Runtime/4.1.0-rc2-23901/ref/netstandard1.3/System.Runtime.dll
--reference:/home/demo/.nuget/packages/System.Runtime.Extensions/4.1.0-rc2-23901/ref/netstandard1.3/System.Runtime.Extensions.dll
--reference:/home/demo/.nuget/packages/System.Runtime.Handles/4.0.1-rc2-23901/ref/netstandard1.3/System.Runtime.Handles.dll
--reference:/home/demo/.nuget/packages/System.Runtime.InteropServices/4.1.0-rc2-23901/ref/netstandard1.3/System.Runtime.InteropServices.dll
--reference:/home/demo/.nuget/packages/System.Runtime.InteropServices.PInvoke/4.0.0-rc2-23901/ref/netstandard1.3/System.Runtime.InteropServices.PInvoke.dll
--reference:/home/demo/.nuget/packages/System.Runtime.InteropServices.RuntimeInformation/4.0.0-rc2-23901/ref/netstandard1.1/System.Runtime.InteropServices.RuntimeInformation.dll
--reference:/home/demo/.nuget/packages/System.Runtime.Loader/4.0.0-rc2-23616/ref/dotnet5.5/System.Runtime.Loader.dll
--reference:/home/demo/.nuget/packages/System.Runtime.Numerics/4.0.1-rc2-23901/ref/netstandard1.1/System.Runtime.Numerics.dll
--reference:/home/demo/.nuget/packages/System.Text.Encoding/4.0.11-rc2-23901/ref/netstandard1.3/System.Text.Encoding.dll
--reference:/home/demo/.nuget/packages/System.Text.Encoding.Extensions/4.0.11-rc2-23901/ref/netstandard1.3/System.Text.Encoding.Extensions.dll
--reference:/home/demo/.nuget/packages/System.Text.RegularExpressions/4.0.12-rc2-23901/ref/netstandard1.3/System.Text.RegularExpressions.dll
--reference:/home/demo/.nuget/packages/System.Threading/4.0.11-rc2-23901/ref/netstandard1.3/System.Threading.dll
--reference:/home/demo/.nuget/packages/System.Threading.Tasks/4.0.11-rc2-23901/ref/netstandard1.3/System.Threading.Tasks.dll
--reference:/home/demo/.nuget/packages/System.Threading.Tasks.Parallel/4.0.1-rc2-23616/ref/dotnet5.2/System.Threading.Tasks.Parallel.dll
--reference:/home/demo/.nuget/packages/System.Threading.Thread/4.0.0-rc2-23616/ref/dotnet5.4/System.Threading.Thread.dll
--reference:/home/demo/.nuget/packages/System.Threading.ThreadPool/4.0.10-rc2-23616/ref/dotnet5.4/System.Threading.ThreadPool.dll
--reference:/home/demo/.nuget/packages/System.Threading.Timer/4.0.1-rc2-23901/ref/netstandard1.2/System.Threading.Timer.dll
--reference:/home/demo/.nuget/packages/runtime.ubuntu.14.04-x64.Microsoft.NETCore.Runtime.CoreCLR/1.0.2-rc2-23901/runtimes/ubuntu.14.04-x64/lib/dotnet/mscorlib.dll
/tmp/coreclr/Program.fs
```

6) Compile the sources with the new response file:

/usr/share/dotnet/bin/dotnet compile-fsc /tmp/coreclr/obj/Debug/netstandardapp1.5/dotnet-compile.rsp

7) Run with corerun:

/usr/share/dotnet/bin/corerun bin/Debug/netstandardapp1.5/coreclr.dll 
Hello World!
[||]

**Comment by enricosada** [comment]
Amazing @zpodlovics , thx !! 
i'll update travis ubuntu build too and add it to wiki

You have a command line for download + unzip ( step1 )? so i can add it to travis (i tried but wasnt working, dunno why)

Atm only `lkg` version works (see [Status](https://github.com/enricosada/fsharp-dotnet-cli-samples/wiki/Status) , lkg is version 1.0.0.001494

the missing mscorlib it's an issues with current `latest` (1.0.0.001638) .net cli ( i need to add that to wiki, it's a new bug ) because compile-fsc choose netcore (system.runtime) vs .net (mscorlib) using `DNXCORE50` compiler directive.
the `latest` pass `--define:NETSTANDARDAPP1_5` . I'll send a pr to .net cli
the `lkg` pass `--define:DNXCORE50`
